### ISSUE TITLE
请问能告诉我下这是哪个应用的头文件吗？

### ISSUE THREAD

**Issue by YaoJuan** [onezens/SmartQQ#1]
[BeaconNetworkUtil getWifiMac]BeaconNetworkUtil.m:75,
我们目前发现项目中这里有一个问题，但是不知道是谁引用了这个库

**Comment by onezens** [comment]
1. 加个符号断点，然后一直点击APP，直到被调用，看调用栈
2. hook方法，打印调用栈信息

**Comment by YaoJuan** [comment]
> 1. 加个符号断点，然后一直点击APP，直到被调用，看调用栈
> 2.hook方法，打印调用栈信息

ok。我已经知道了
